import { CheckCircle2, CircleSlash2, Clock3, RefreshCw, UserRoundCheck } from "lucide-react";
import type { McpTraceStep } from "@/types/mcp-practice";

export function McpTraceTable({ trace }: { trace: McpTraceStep[] }) {
  return <section aria-labelledby="trace-title"><div><h3 id="trace-title" className="text-sm font-semibold text-slate-950">调用 Trace</h3><p className="mt-1 text-xs text-slate-500">仅展示产品级步骤与脱敏输入，不包含隐藏提示词、模型推理过程或 chain-of-thought。</p></div><div className="mt-4 overflow-x-auto rounded-md border border-slate-200 bg-white"><table className="min-w-[1050px] w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["时间 / 步骤","工具","脱敏输入摘要","权限决策","状态","耗时","重试","成本","Evidence ID"].map((item) => <th key={item} className="border-b border-slate-200 px-3 py-3">{item}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{trace.map((item) => <tr key={`${item.step}-${item.tool}`} className="align-top"><td className="px-3 py-3"><span className="text-slate-500">{item.time}</span><span className="ml-2 font-semibold text-slate-900">#{item.step}</span></td><td className="px-3 py-3 font-mono font-semibold text-slate-900">{item.tool}</td><td className="max-w-[300px] px-3 py-3 font-mono leading-5 text-slate-600">{item.redactedInput}</td><td className="px-3 py-3 text-slate-600">{decisionLabel[item.permissionDecision]}</td><td className="px-3 py-3"><TraceStatus status={item.status} /></td><td className="px-3 py-3 text-slate-600">{item.latencyMs} ms</td><td className="px-3 py-3 text-slate-600">{item.retries}</td><td className="px-3 py-3 font-mono text-slate-600">${item.costUsd.toFixed(4)}</td><td className="px-3 py-3 font-mono text-blue-700">{item.evidenceId}</td></tr>)}</tbody></table></div></section>;
}

const decisionLabel = { pending: "待决定", allowed: "已允许", denied: "已拒绝", not_required: "无需确认" };
function TraceStatus({ status }: { status: McpTraceStep["status"] }) { const map = { success: [CheckCircle2,"成功","text-emerald-700"], blocked: [CircleSlash2,"阻断","text-rose-700"], timeout: [Clock3,"超时","text-amber-700"], degraded: [RefreshCw,"降级","text-amber-700"], review_created: [UserRoundCheck,"已建审核","text-blue-700"] } as const; const [Icon,label,color] = map[status]; return <span className={`inline-flex items-center gap-1 font-medium ${color}`}><Icon className="h-3 w-3" />{label}</span>; }
