import Link from "next/link";
import { ArrowUpRight, Ban, CheckCircle2, CircleStop, UserRoundCheck } from "lucide-react";
import { mcpProductBoundaries } from "@/data/mcp-practice";

export function ProductBoundaries() {
  return <section aria-labelledby="boundaries-title" className="space-y-6"><div><p className="text-xs font-semibold uppercase text-blue-600">Product guardrails</p><h2 id="boundaries-title" className="mt-2 text-2xl font-semibold text-slate-950">产品边界与责任人</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">MCP 只是受治理任务执行的接口。产品规则决定何时允许、拒绝和交给人。</p></div><div className="grid gap-6 lg:grid-cols-2"><Boundary icon={CheckCircle2} title="允许" items={mcpProductBoundaries.allowed} color="text-emerald-600" /><Boundary icon={Ban} title="禁止" items={mcpProductBoundaries.forbidden} color="text-rose-600" /><Boundary icon={CircleStop} title="何时拒绝" items={mcpProductBoundaries.refusal} color="text-amber-600" /><Boundary icon={UserRoundCheck} title="何时接管" items={mcpProductBoundaries.handoff} color="text-blue-600" /></div><div className="border-l-4 border-slate-900 bg-white p-5"><p className="text-xs font-semibold text-slate-500">审核责任</p><p className="mt-2 text-sm leading-6 text-slate-700">{mcpProductBoundaries.owner}</p></div><div className="grid gap-px overflow-hidden rounded-md border border-slate-200 bg-slate-200 sm:grid-cols-3"><Related href="/metric-registry" label="Metric Registry" description="查看 GMV 口径、Owner 与维度" /><Related href="/review" label="Analyst Review" description="查看人工审核与治理队列" /><Related href="/ops" label="Product Ops" description="查看误拒、质量与运营反馈" /></div></section>;
}

function Boundary({ icon: Icon, title, items, color }: { icon: typeof CheckCircle2; title: string; items: string[]; color: string }) { return <div className="border-t border-slate-200 pt-5"><div className="flex items-center gap-2"><Icon className={`h-4 w-4 ${color}`} /><h3 className="text-sm font-semibold text-slate-950">{title}</h3></div><ul className="mt-4 space-y-2">{items.map((item) => <li key={item} className="text-sm leading-6 text-slate-600">{item}</li>)}</ul></div>; }
function Related({ href, label, description }: { href: string; label: string; description: string }) { return <Link href={href} className="group bg-white p-5 hover:bg-slate-50"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-slate-950">{label}</p><ArrowUpRight className="h-4 w-4 text-slate-400 group-hover:text-blue-600" /></div><p className="mt-2 text-xs leading-5 text-slate-500">{description}</p></Link>; }
